import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import {
  basename,
  dirname,
  isAbsolute,
  join,
  relative,
  resolve,
} from "node:path";
import { isNsid } from "@atcute/lexicons/syntax";
import type { CAC } from "cac";
import {
  contractFromManifest,
  digestLexiconDocuments,
  digestPublicContract,
  isPublicServiceManifest,
  normalizePublicServiceEndpoint,
  validateManifestContract,
  type PublicServiceAuthContract,
  type PublicServiceManifest,
} from "../../public-service.js";
import { generateLexiconTypesWithAtcute } from "../atcute.js";

const MAX_DISCOVERY_BYTES = 10 * 1024 * 1024;
const REQUEST_TIMEOUT_MS = 15_000;

const LEXICON_CONFIG_NAMES = [
  "lex.config.js",
  "lex.config.mjs",
  "lex.config.cjs",
  "lex.config.ts",
  "lex.config.mts",
  "lex.config.cts",
];

interface ConnectOptions {
  root: string;
  out: string;
  lock: string;
  client: string;
  clientTypes: string;
  generate?: boolean;
  skipClient?: boolean;
  update?: boolean;
}

export interface ProviderLock {
  format: "contrail.provider-lock";
  version: 1;
  endpoint: string;
  namespace: string;
  contractDigest: string;
  lexiconDigest: string;
  methods: string[];
  collections: string[];
  serviceAuth: PublicServiceAuthContract | null;
  lexiconRoot: string;
}

async function readJson(response: Response, label: string): Promise<unknown> {
  if (!response.ok) {
    throw new Error(
      `${label} request failed: ${response.status} ${response.statusText}`,
    );
  }
  const declaredLength = Number(response.headers.get("content-length") ?? 0);
  if (declaredLength > MAX_DISCOVERY_BYTES) {
    throw new Error(`${label} exceeds ${MAX_DISCOVERY_BYTES} bytes`);
  }
  const text = await response.text();
  if (new TextEncoder().encode(text).byteLength > MAX_DISCOVERY_BYTES) {
    throw new Error(`${label} exceeds ${MAX_DISCOVERY_BYTES} bytes`);
  }
  try {
    return JSON.parse(text) as unknown;
  } catch {
    throw new Error(`${label} is not valid JSON`);
  }
}

async function fetchJson(
  fetcher: typeof fetch,
  url: string | URL,
  label: string,
  timeoutMs: number,
): Promise<unknown> {
  const requested = new URL(url);
  const response = await fetcher(requested, {
    signal: AbortSignal.timeout(timeoutMs),
  });
  if (response.url && new URL(response.url).origin !== requested.origin) {
    throw new Error(`${label} redirected to a different origin`);
  }
  return readJson(response, label);
}

function resolveInsideRoot(
  root: string,
  value: string,
  options: { allowRoot?: boolean } = {},
): string {
  const target = resolve(root, value);
  const rel = relative(root, target);
  if (
    (!options.allowRoot && rel === "") ||
    rel === ".." ||
    rel.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`) ||
    isAbsolute(rel)
  ) {
    throw new Error(`path must stay inside the consumer project: ${value}`);
  }
  return target;
}

function lexiconPath(root: string, id: string): string {
  if (!isNsid(id)) throw new Error(`invalid Lexicon NSID: ${id}`);
  return resolve(root, ...id.split(".")) + ".json";
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function formatStringArray(
  values: readonly string[],
  indentation: number,
): string {
  if (values.length === 0) return "[]";
  const items = values
    .map((value) => `${" ".repeat(indentation + 2)}${JSON.stringify(value)},`)
    .join("\n");
  return `[\n${items}\n${" ".repeat(indentation)}]`;
}

const GENERATED_LEXICON_CONFIG_HEADER =
  "// Generated by `contrail connect`. Re-run the command to update; do not edit.\n";

/** Create a dependency-free Atcute config containing the connected service
 * metadata. Unmarked JavaScript or TypeScript configs remain consumer-owned. */
export async function ensureConsumerLexiconConfig(options: {
  root: string;
  out: string;
  types?: string;
  lock: ProviderLock;
}): Promise<{ path: string; created: boolean; updated: boolean }> {
  const root = resolve(options.root);
  let path = join(root, "lex.config.js");
  for (const name of LEXICON_CONFIG_NAMES) {
    const candidate = join(root, name);
    if (await exists(candidate)) {
      path = candidate;
      break;
    }
  }

  const lexiconRoot = resolveInsideRoot(root, options.out);
  const patternRoot = relative(root, lexiconRoot).replaceAll("\\", "/");
  const typesIndex = resolveInsideRoot(
    root,
    options.types ?? "src/contrail/types/index.ts",
  );
  const typesRoot = relative(root, dirname(typesIndex)).replaceAll("\\", "/");
  const serviceDid = options.lock.serviceAuth?.audience ?? null;
  const scope = serviceDid ? `rpc?lxm=*&aud=${serviceDid}` : null;
  const source = `${GENERATED_LEXICON_CONFIG_HEADER}export default {\n  contrail: {\n    endpoint: ${JSON.stringify(options.lock.endpoint)},\n    serviceDid: ${JSON.stringify(serviceDid)},\n    scope: ${JSON.stringify(scope)},\n    collections: ${formatStringArray(options.lock.collections, 4)},\n  },\n  generate: {\n    files: [${JSON.stringify(`${patternRoot}/**/*.json`)}],\n    outdir: ${JSON.stringify(`${typesRoot}/`)},\n  },\n};\n`;

  if (await exists(path)) {
    const current = await readFile(path, "utf8");
    if (
      !current.startsWith(GENERATED_LEXICON_CONFIG_HEADER) ||
      current === source
    ) {
      return { path, created: false, updated: false };
    }
    const stagedDirectory = await mkdtemp(join(dirname(path), ".contrail-lex-"));
    const staged = join(stagedDirectory, basename(path));
    try {
      await writeFile(staged, source);
      await rename(staged, path);
    } finally {
      await rm(stagedDirectory, { recursive: true, force: true });
    }
    return { path, created: false, updated: true };
  }

  try {
    await writeFile(path, source, { flag: "wx" });
    return { path, created: true, updated: false };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "EEXIST") {
      return { path, created: false, updated: false };
    }
    throw error;
  }
}

const GENERATED_CLIENT_HEADER =
  "// Generated by `contrail connect`. Re-run the command to update; do not edit.\n";

/** Create the small provider-specific module used by application and OAuth
 * setup code. Unmarked TypeScript or JavaScript modules remain consumer-owned. */
export async function ensureConsumerClientModule(options: {
  root: string;
  file?: string;
  types?: string;
  lock: ProviderLock;
}): Promise<{ path: string; created: boolean; updated: boolean }> {
  const root = resolve(options.root);
  const requested = options.file ?? "src/contrail/index.ts";
  const defaultNames = ["src/contrail/index.ts", "src/contrail/index.js"];
  let selected = requested;
  if (defaultNames.includes(requested)) {
    for (const name of defaultNames) {
      if (await exists(join(root, name))) {
        selected = name;
        break;
      }
    }
  }
  if (!/\.(?:ts|js)$/.test(selected)) {
    throw new Error("Contrail client module must end in .ts or .js");
  }

  const path = resolveInsideRoot(root, selected);
  const isTypeScript = selected.endsWith(".ts");
  let generatedImport = "";
  if (isTypeScript) {
    const types = resolveInsideRoot(
      root,
      options.types ?? "src/contrail/types/index.ts",
    );
    let specifier = relative(dirname(path), types).replaceAll("\\", "/");
    specifier = specifier.replace(/\.(?:ts|js)$/, ".js");
    if (!specifier.startsWith(".")) specifier = `./${specifier}`;
    generatedImport = `import type {} from ${JSON.stringify(specifier)};\n`;
  }
  const serviceDid = options.lock.serviceAuth?.audience;
  const scope = serviceDid ? `rpc?lxm=*&aud=${serviceDid}` : null;
  const protectedMethods =
    options.lock.serviceAuth?.methods.map(({ id }) => id) ?? [];
  const serviceMethods = [
    ...new Set([...options.lock.methods, ...protectedMethods]),
  ].sort();
  const notifyMethod = protectedMethods.find(
    (method) => method === `${options.lock.namespace}.notifyOfUpdate`,
  );
  const source = `${GENERATED_CLIENT_HEADER}import { createPublicServiceClient } from "@atmo-dev/contrail/client";\n${generatedImport}\nexport const contrail = createPublicServiceClient({\n  endpoint: ${JSON.stringify(options.lock.endpoint)},${serviceDid ? `\n  serviceDid: ${JSON.stringify(serviceDid)},\n  scope: ${JSON.stringify(scope)},` : ""}\n  serviceMethods: ${formatStringArray(serviceMethods, 2)},\n  collections: ${formatStringArray(options.lock.collections, 2)},${notifyMethod ? `\n  notifyMethod: ${JSON.stringify(notifyMethod)},` : ""}\n});\n`;
  await mkdir(dirname(path), { recursive: true });

  if (await exists(path)) {
    const current = await readFile(path, "utf8");
    if (!current.startsWith(GENERATED_CLIENT_HEADER) || current === source) {
      return { path, created: false, updated: false };
    }
    const stagedDirectory = await mkdtemp(join(dirname(path), ".contrail-client-"));
    const staged = join(stagedDirectory, basename(path));
    try {
      await writeFile(staged, source);
      await rename(staged, path);
    } finally {
      await rm(stagedDirectory, { recursive: true, force: true });
    }
    return { path, created: false, updated: true };
  }

  try {
    await writeFile(path, source, { flag: "wx" });
    return { path, created: true, updated: false };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "EEXIST") {
      return { path, created: false, updated: false };
    }
    throw error;
  }
}

export async function connectPublicService(options: {
  endpoint: string;
  root: string;
  out: string;
  lock: string;
  fetcher?: typeof fetch;
  update?: boolean;
  /** @internal Shorter timeout for deterministic connection tests. */
  timeoutMs?: number;
}): Promise<{
  manifest: PublicServiceManifest;
  lock: ProviderLock;
  written: number;
}> {
  const endpoint = normalizePublicServiceEndpoint(options.endpoint);
  const projectRoot = resolve(options.root);
  const lockPath = resolveInsideRoot(projectRoot, options.lock);
  if (!options.update) {
    try {
      await readFile(lockPath, "utf8");
      throw new Error(
        "a Contrail provider lock already exists; rerun with --update",
      );
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  }
  const fetcher = options.fetcher ?? fetch;
  const manifestValue = await fetchJson(
    fetcher,
    `${endpoint}/.well-known/contrail`,
    "Contrail manifest",
    options.timeoutMs ?? REQUEST_TIMEOUT_MS,
  );
  if (!isPublicServiceManifest(manifestValue)) {
    throw new Error("response is not a supported Contrail service manifest");
  }
  const manifest = manifestValue;
  if (normalizePublicServiceEndpoint(manifest.endpoint) !== endpoint) {
    throw new Error(
      `manifest endpoint mismatch: expected ${endpoint}, received ${manifest.endpoint}`,
    );
  }
  const lexiconUrl = new URL(manifest.lexicons.url);
  const statusUrl = new URL(manifest.status.url);
  if (
    lexiconUrl.origin !== endpoint ||
    lexiconUrl.username !== "" ||
    lexiconUrl.password !== "" ||
    statusUrl.origin !== endpoint ||
    statusUrl.username !== "" ||
    statusUrl.password !== ""
  ) {
    throw new Error("manifest resource URLs must use the service origin");
  }
  const lexiconValue = await fetchJson(
    fetcher,
    lexiconUrl,
    "Contrail Lexicons",
    options.timeoutMs ?? REQUEST_TIMEOUT_MS,
  );
  const values = (lexiconValue as { lexicons?: unknown })?.lexicons;
  if (!Array.isArray(values)) {
    throw new Error("Lexicon response must contain a lexicons array");
  }
  const { lexicons, digest } = await digestLexiconDocuments(values as object[]);
  if (digest !== manifest.lexicons.digest) {
    throw new Error(
      `Lexicon digest mismatch: manifest=${manifest.lexicons.digest}, fetched=${digest}`,
    );
  }
  validateManifestContract(manifest, lexicons);
  const contractDigest = await digestPublicContract(
    contractFromManifest(manifest),
  );
  if (contractDigest !== manifest.contract.digest) {
    throw new Error(
      `Contract digest mismatch: manifest=${manifest.contract.digest}, computed=${contractDigest}`,
    );
  }

  const outputRoot = resolveInsideRoot(projectRoot, options.out);
  const providerKey = new URL(endpoint).host.replace(/[^a-zA-Z0-9.-]/g, "_");
  const providerRoot = resolveInsideRoot(outputRoot, providerKey);
  await mkdir(outputRoot, { recursive: true });
  const stagedProvider = await mkdtemp(join(outputRoot, `.${providerKey}-`));
  for (const document of lexicons) {
    const path = lexiconPath(stagedProvider, document.id);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, `${JSON.stringify(document, null, 2)}\n`);
  }

  const lock: ProviderLock = {
    format: "contrail.provider-lock",
    version: 1,
    endpoint,
    namespace: manifest.namespace,
    contractDigest: manifest.contract.digest,
    lexiconDigest: manifest.lexicons.digest,
    methods: [...manifest.methods].sort(),
    collections: [
      ...new Set(manifest.collections.map(({ nsid }) => nsid)),
    ].sort(),
    serviceAuth: manifest.serviceAuth ?? null,
    lexiconRoot: relative(projectRoot, providerRoot),
  };
  const lockDirectory = dirname(lockPath);
  await mkdir(lockDirectory, { recursive: true });
  const stagedLockDirectory = await mkdtemp(
    join(lockDirectory, `.${basename(lockPath)}-`),
  );
  const stagedLock = join(stagedLockDirectory, basename(lockPath));
  await writeFile(stagedLock, `${JSON.stringify(lock, null, 2)}\n`);

  const backupRoot = join(
    outputRoot,
    `.${providerKey}.backup-${process.pid}-${Date.now()}`,
  );
  const backupLock = join(
    lockDirectory,
    `.${basename(lockPath)}.backup-${process.pid}-${Date.now()}`,
  );
  const hadProvider = await exists(providerRoot);
  const hadLock = await exists(lockPath);
  try {
    if (hadProvider) await rename(providerRoot, backupRoot);
    if (hadLock) await rename(lockPath, backupLock);
    await rename(stagedProvider, providerRoot);
    await rename(stagedLock, lockPath);
    await rm(backupRoot, { recursive: true, force: true });
    await rm(backupLock, { force: true });
  } catch (error) {
    await rm(providerRoot, { recursive: true, force: true });
    await rm(lockPath, { force: true });
    if (hadProvider && (await exists(backupRoot))) {
      await rename(backupRoot, providerRoot);
    }
    if (hadLock && (await exists(backupLock))) {
      await rename(backupLock, lockPath);
    }
    throw error;
  } finally {
    await rm(stagedProvider, { recursive: true, force: true });
    await rm(stagedLockDirectory, { recursive: true, force: true });
    await rm(backupRoot, { recursive: true, force: true });
    await rm(backupLock, { force: true });
  }
  return { manifest, lock, written: lexicons.length };
}

export function registerConnect(cli: CAC): void {
  cli
    .command(
      "connect <endpoint>",
      "Discover a public Contrail, lock its API, and generate a typed client",
    )
    .option("--root <path>", "Consumer project root", {
      default: process.cwd(),
    })
    .option("--out <path>", "Provider-owned Lexicon storage relative to root", {
      default: "src/contrail/lexicons",
    })
    .option("--lock <path>", "Provider lock file relative to root", {
      default: "contrail.lock.json",
    })
    .option("--client <path>", "Generated client module (.ts or .js)", {
      default: "src/contrail/index.ts",
    })
    .option("--client-types <path>", "Generated Lexicon index imported by a TypeScript client", {
      default: "src/contrail/types/index.ts",
    })
    .option("--skip-client", "Do not create a provider client module")
    .option("--update", "Replace an existing provider lock and owned Lexicons")
    .option("--no-generate", "Pull and lock without generating types or a client module")
    .action(async (endpoint: string, options: ConnectOptions) => {
      const result = await connectPublicService({
        endpoint,
        root: options.root,
        out: options.out,
        lock: options.lock,
        update: options.update,
      });
      console.log(
        `connected ${result.lock.endpoint}: ${result.written} Lexicons, contract ${result.lock.contractDigest}`,
      );
      if (options.generate !== false) {
        const config = await ensureConsumerLexiconConfig({
          root: options.root,
          out: options.out,
          types: options.clientTypes,
          lock: result.lock,
        });
        if (config.created) {
          console.log(`created ${relative(resolve(options.root), config.path)}`);
        } else if (config.updated) {
          console.log(`updated ${relative(resolve(options.root), config.path)}`);
        }
        generateLexiconTypesWithAtcute(resolve(options.root));
        if (!options.skipClient) {
          const client = await ensureConsumerClientModule({
            root: options.root,
            file: options.client,
            types: options.clientTypes,
            lock: result.lock,
          });
          if (client.created) {
            console.log(`created ${relative(resolve(options.root), client.path)}`);
          } else if (client.updated) {
            console.log(`updated ${relative(resolve(options.root), client.path)}`);
          }
        }
      }
    });
}
