// Generated by `vite build` before Wrangler bundles this entrypoint.
// @ts-expect-error SvelteKit's Cloudflare adapter writes this module at build time.
import app from "./.svelte-kit/cloudflare/_worker.js";
import { SpaceSubscriptionHub as BaseSpaceSubscriptionHub } from "@atmo-dev/contrail-spaces-alpha/worker";
import { spaces, type SpacesDemoEnv } from "./src/lib/server/spaces";

export class SpaceSubscriptionHub extends BaseSpaceSubscriptionHub {}

function isSpacesProtocolRequest(request: Request): boolean {
  const url = new URL(request.url);
  if (url.pathname === "/subscribe") return true;
  if (
    url.pathname === "/.well-known/did.json" ||
    url.pathname === "/.well-known/contrail-spaces-alpha" ||
    url.pathname === "/lexicons"
  ) return true;
  return url.pathname === "/xrpc/com.atproto.space.notifyWrite" ||
    url.pathname === "/xrpc/com.atproto.space.notifySpaceDeleted";
}

export default {
  fetch(request: Request, env: SpacesDemoEnv, ctx: ExecutionContext) {
    if (isSpacesProtocolRequest(request)) {
      return spaces.fetch!(request, env, ctx);
    }
    const integratedEnv = Object.assign(Object.create(env), {
      SPACES_RUNTIME: spaces.integrated(env, ctx),
    });
    return app.fetch(request, integratedEnv, ctx);
  },
  queue(batch, env, ctx) {
    return spaces.queue!(batch, env, ctx);
  },
  scheduled(controller, env, ctx) {
    return spaces.scheduled!(controller, env, ctx);
  },
} satisfies ExportedHandler<SpacesDemoEnv>;
